/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class Calculatrice extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculatrice.class.getName());
    double premiernombre=0;
    String operation="";
    double resultat =0;
    double deuxiemenombre=0;
    
    /**
     * Creates new form Calculatrice
     */
    public Calculatrice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ecran = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        un = new javax.swing.JButton();
        deux = new javax.swing.JButton();
        trois = new javax.swing.JButton();
        quatre = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cinq = new javax.swing.JButton();
        six = new javax.swing.JButton();
        sept = new javax.swing.JButton();
        huit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        neuf = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        moins = new javax.swing.JButton();
        fois = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        division = new javax.swing.JButton();
        pourcent = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        ToutSuppr = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        point = new javax.swing.JButton();
        egal = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        carre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(6, 1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        ecran.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ecran.addActionListener(this::ecranActionPerformed);
        jPanel3.add(ecran);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        un.setText("1");
        un.addActionListener(this::unActionPerformed);
        jPanel4.add(un);

        deux.setText("2");
        deux.addActionListener(this::deuxActionPerformed);
        jPanel4.add(deux);

        trois.setText("3");
        trois.addActionListener(this::troisActionPerformed);
        jPanel4.add(trois);

        quatre.setText("4");
        quatre.addActionListener(this::quatreActionPerformed);
        jPanel4.add(quatre);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4));

        cinq.setText("5");
        cinq.addActionListener(this::cinqActionPerformed);
        jPanel5.add(cinq);

        six.setText("6");
        six.addActionListener(this::sixActionPerformed);
        jPanel5.add(six);

        sept.setText("7");
        sept.addActionListener(this::septActionPerformed);
        jPanel5.add(sept);

        huit.setText("8");
        huit.addActionListener(this::huitActionPerformed);
        jPanel5.add(huit);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 4));

        neuf.setText("9");
        neuf.addActionListener(this::neufActionPerformed);
        jPanel6.add(neuf);

        zero.setText("0");
        zero.addActionListener(this::zeroActionPerformed);
        jPanel6.add(zero);

        moins.setText("-");
        moins.addActionListener(this::moinsActionPerformed);
        jPanel6.add(moins);

        fois.setText("x");
        fois.addActionListener(this::foisActionPerformed);
        jPanel6.add(fois);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 4));

        division.setText("/");
        division.addActionListener(this::divisionActionPerformed);
        jPanel7.add(division);

        pourcent.setText("%");
        pourcent.addActionListener(this::pourcentActionPerformed);
        jPanel7.add(pourcent);

        supprimer.setText("Suppr");
        supprimer.addActionListener(this::supprimerActionPerformed);
        jPanel7.add(supprimer);

        ToutSuppr.setText("C");
        ToutSuppr.addActionListener(this::ToutSupprActionPerformed);
        jPanel7.add(ToutSuppr);

        jPanel1.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 4));

        point.setText(".");
        point.setPreferredSize(new java.awt.Dimension(50, 50));
        point.addActionListener(this::pointActionPerformed);
        jPanel8.add(point);

        egal.setText("=");
        egal.addActionListener(this::egalActionPerformed);
        jPanel8.add(egal);

        plus.setText("+");
        plus.addActionListener(this::plusActionPerformed);
        jPanel8.add(plus);

        carre.setText("Puissance 2");
        carre.addActionListener(this::carreActionPerformed);
        jPanel8.add(carre);

        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
ecran.setText(ecran.getText() +1); 
    }//GEN-LAST:event_unActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        String text=ecran.getText();
        if (text.length()>0) {
            String newtext = text.substring(0, text.length()-1);
            ecran.setText(newtext);
        
        }    // TODO add your handling code here:
    }//GEN-LAST:event_supprimerActionPerformed

    private void ToutSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToutSupprActionPerformed
     ecran.setText(""); 
     premiernombre=0;
     deuxiemenombre=0;
    }//GEN-LAST:event_ToutSupprActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
 ecran.setText(ecran.getText() +".");      // TODO add your handling code here:;
    }//GEN-LAST:event_pointActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
  premiernombre= Double.parseDouble(ecran.getText());
  operation="+";
  ecran.setText("");
  // TODO add your handling code here:
    }//GEN-LAST:event_plusActionPerformed

    private void ecranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecranActionPerformed

    private void deuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deuxActionPerformed
ecran.setText(ecran.getText() +2);        // TODO add your handling code here:
    }//GEN-LAST:event_deuxActionPerformed

    private void troisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troisActionPerformed
ecran.setText(ecran.getText() +3);        // TODO add your handling code here:
    }//GEN-LAST:event_troisActionPerformed

    private void quatreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatreActionPerformed
ecran.setText(ecran.getText() +4);        // TODO add your handling code here:
    }//GEN-LAST:event_quatreActionPerformed

    private void cinqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinqActionPerformed
ecran.setText(ecran.getText() +5);        // TODO add your handling code here:
    }//GEN-LAST:event_cinqActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
ecran.setText(ecran.getText() +6);        // TODO add your handling code here:
    }//GEN-LAST:event_sixActionPerformed

    private void septActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_septActionPerformed
ecran.setText(ecran.getText() +7);        // TODO add your handling code here:
    }//GEN-LAST:event_septActionPerformed

    private void huitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huitActionPerformed
ecran.setText(ecran.getText() +8);        // TODO add your handling code here:
    }//GEN-LAST:event_huitActionPerformed

    private void neufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neufActionPerformed
ecran.setText(ecran.getText() +9);        // TODO add your handling code here:
    }//GEN-LAST:event_neufActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
ecran.setText(ecran.getText() +0);        // TODO add your handling code here:
    }//GEN-LAST:event_zeroActionPerformed

    private void egalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egalActionPerformed
deuxiemenombre=Double.parseDouble(ecran.getText());
switch(operation){
case"+":resultat= premiernombre + deuxiemenombre ;break;
case"-":resultat= premiernombre - deuxiemenombre ;break;
case"/":if(deuxiemenombre!=0){resultat= premiernombre + deuxiemenombre ;}
case"%":resultat =(premiernombre/100)*deuxiemenombre;}  
ecran.setText(String.valueOf(resultat));
// TODO add your handling code here:
    }//GEN-LAST:event_egalActionPerformed

    private void moinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moinsActionPerformed
premiernombre= Double.parseDouble(ecran.getText());
  operation="-";
  ecran.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_moinsActionPerformed

    private void foisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foisActionPerformed
premiernombre= Double.parseDouble(ecran.getText());
  operation="*";
  ecran.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_foisActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
premiernombre= Double.parseDouble(ecran.getText());
  operation="/";
  ecran.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_divisionActionPerformed

    private void pourcentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pourcentActionPerformed
premiernombre= Double.parseDouble(ecran.getText());
  operation="%";
  ecran.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_pourcentActionPerformed

    private void carreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreActionPerformed
  premiernombre= Double.parseDouble(ecran.getText());
  double resultat= premiernombre *premiernombre;
  ecran.setText(String.valueOf(resultat));      // TODO add your handling code here:
    }//GEN-LAST:event_carreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculatrice().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToutSuppr;
    private javax.swing.JButton carre;
    private javax.swing.JButton cinq;
    private javax.swing.JButton deux;
    private javax.swing.JButton division;
    private javax.swing.JTextField ecran;
    private javax.swing.JButton egal;
    private javax.swing.JButton fois;
    private javax.swing.JButton huit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton moins;
    private javax.swing.JButton neuf;
    private javax.swing.JButton plus;
    private javax.swing.JButton point;
    private javax.swing.JButton pourcent;
    private javax.swing.JButton quatre;
    private javax.swing.JButton sept;
    private javax.swing.JButton six;
    private javax.swing.JButton supprimer;
    private javax.swing.JButton trois;
    private javax.swing.JButton un;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
